networks:
  db-data-net:
    driver: bridge
services:
  pythonapp:
    image: app:1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8000"
    environment:
      - DB_HOST=mysql
    networks:
      - db-data-net
    depends_on:
      - mysql
    restart: unless-stopped
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=1234
    networks:
      - db-data-net
volumes:
  db-data: